# Data Source Properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apple_store?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}

# Multipart settings
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


# JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update

# MVC Properties
  mvc:
    hidden-method:
      filter:
        enabled: true

# Logging Levels
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

# Cloudinary
cloudinary:
  name: ${CLOUDINARY_NAME:dwgx3lz5l}
  api-key: ${CLOUDINARY_API_KEY:952728852841552}
  api-secret: ${CLOUDINARY_API_SECRET:6lRJ3v01NhjijHLchvvUS_-1bKM}

# Administrator
admin:
  username: ${ADMIN_USERNAME:antoaneta}
  password: ${ADMIN_PASSWORD:aa1aa}
  first-name: ${ADMIN_FIRST_NAME:Antoaneta}
  last-name: ${ADMIN_LAST_NAME:Cherkezova}
  email: ${ADMIN_EMAIL:admin@gmail.com}
  age: ${ADMIN_AGE:33}
  city: ${ADMIN_CITY:Burgas}
  phone-number: ${ADMIN_PHONE_NUMBER:123-456-789}
